import Layout from "@/app/components/Layout";
import "./globals.css";
import { Nunito } from "next/font/google";
import ClientOnly from "@/app/components/ClientOnly";
import LoginModal from "@/app/components/models/LoginModal";
import RegisterModal from "@/app/components/models/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import ReviewModal from "@/app/components/models/ReviewModal";


const font = Nunito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  
  return (
    <html lang="en">
      <body className={font.className}>
        <main>
          <ClientOnly>
            <LoginModal />
            <RegisterModal />
            <ToasterProvider />
            <ReviewModal />
          </ClientOnly>
          <Layout>{children}</Layout>
        </main>
      </body>
    </html>
  );
}
